# Generated by Django 2.1.7 on 2019-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_topic_made_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='calories',
            field=models.SmallIntegerField(default=1, verbose_name='количество калорий'),
        ),
        migrations.AddField(
            model_name='topic',
            name='food_type',
            field=models.CharField(choices=[('MC', 'Второе/горячее'), ('FC', 'Первое'), ('SD', 'Салаты'), ('DR', 'Напитки')], default='MC', max_length=2),
        ),
    ]
