# Generated by Django 2.1.7 on 2019-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190314_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.SmallIntegerField(default=40, verbose_name='Стоимость (в рублях)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='calories',
            field=models.SmallIntegerField(default=1, verbose_name='Количество калорий'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='food_type',
            field=models.CharField(choices=[('MC', 'Второе/горячее'), ('FC', 'Первое'), ('SD', 'Салаты'), ('DR', 'Напитки')], default='MC', max_length=2, verbose_name='Тип блюда'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
