# Generated by Django 2.1.7 on 2019-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190314_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=255, verbose_name='Блюдо')),
                ('calories', models.SmallIntegerField(default=1, verbose_name='Количество калорий')),
                ('price', models.SmallIntegerField(default=40, verbose_name='Стоимость (в рублях)')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='weigth',
            field=models.SmallIntegerField(default=100, verbose_name='Масса блюда (в граммах)'),
        ),
    ]
